// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBc5BkJepP8cSezGRpDyS_lyhqLHa1hPa0',
    appId: '1:403637855318:web:b54cc77900632ff9a787f7',
    messagingSenderId: '403637855318',
    projectId: 'pet-store-5c00f',
    authDomain: 'pet-store-5c00f.firebaseapp.com',
    databaseURL: 'https://pet-store-5c00f-default-rtdb.firebaseio.com',
    storageBucket: 'pet-store-5c00f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuNDbMsvHisC1_ldUnupD-PGrLHxh9m-Q',
    appId: '1:403637855318:android:2806961ab12de6d8a787f7',
    messagingSenderId: '403637855318',
    projectId: 'pet-store-5c00f',
    databaseURL: 'https://pet-store-5c00f-default-rtdb.firebaseio.com',
    storageBucket: 'pet-store-5c00f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLiC8puQ_Rdh5voDD05Cihj5QWg1uSAJ8',
    appId: '1:403637855318:ios:1b5d3f3fdb4a8f15a787f7',
    messagingSenderId: '403637855318',
    projectId: 'pet-store-5c00f',
    databaseURL: 'https://pet-store-5c00f-default-rtdb.firebaseio.com',
    storageBucket: 'pet-store-5c00f.appspot.com',
    iosBundleId: 'com.example.petStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLiC8puQ_Rdh5voDD05Cihj5QWg1uSAJ8',
    appId: '1:403637855318:ios:1b5d3f3fdb4a8f15a787f7',
    messagingSenderId: '403637855318',
    projectId: 'pet-store-5c00f',
    databaseURL: 'https://pet-store-5c00f-default-rtdb.firebaseio.com',
    storageBucket: 'pet-store-5c00f.appspot.com',
    iosBundleId: 'com.example.petStore',
  );
}
